quarkus:
  package:
    jar:
      enabled: true
  http:
    port: 8085
  devservices:
    enabled: false
  kafka:
    devservices:
      enabled: false
  datasource:
    db-kind: mysql
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456789}
    reactive:
      url: vertx-reactive:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/phone_recharge_db
  hibernate-orm:
    database:
      generation: none
      version-check:
        enabled: false

mp:
  messaging:
    outgoing:
      topup-requests:
        connector: smallrye-kafka
        topic: topup-topic
        bootstrap:
          servers: ${KAFKA_BROKERS:PLAINTEXT://localhost:19092,PLAINTEXT://localhost:29092}
        schema:
          registry:
            url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          subject:
            name:
              strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
        specific:
          avro:
            reader: false
        auto:
          register:
            schemas: true
        use:
          latest:
            version: true
