quarkus:
  package:
    jar:
      enabled: true
  http:
    port: 8085
  devservices:
    enabled: false
  kafka:
    devservices:
      enabled: false
  datasource:
    db-kind: mysql
    username: root
    password: 123456789
    reactive:
      url: vertx-reactive:mysql://localhost:3307/phone_recharge_db
  hibernate-orm:
    database:
      generation: none
      version-check:
        enabled: false

mp:
  messaging:
    outgoing:
      topup-requests:
        connector: smallrye-kafka
        topic: topup-topic
        bootstrap:
          servers: ${CONFIG_KAFKA_BROKERS:PLAINTEXT://localhost:19092,PLAINTEXT://localhost:29092}
        schema:
          registry:
            url: ${CONFIG_SCHEMA_REGISTRY_URL:http://localhost:8081}
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          subject:
            name:
              strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
        specific:
          avro:
            reader: false
        auto:
          register:
            schemas: true
        use:
          latest:
            version: true
