quarkus:
  package:
    jar:
      enabled: true
  http:
    port: 9091
    test-port: 0
  devservices:
    enabled: false
  kafka:
    devservice:
      enabled: false
  datasource:
    db-kind: mysql
    username: root
    password: 123456789
    reactive:
      url: vertx-reactive:mysql://localhost:3307/phone_recharge_db
  hibernate-orm:
    database:
      generation: none
      version-check:
        enabled: false

mp:
  messaging:
    outgoing:
      topup-requests:
        connector: smallrye-kafka
        topic: topup-topic
        bootstrap:
          servers: ${CONFIG_KAFKA_BROKERS:PLAINTEXT://localhost:19092,PLAINTEXT://localhost:29092}
        schema:
          registry:
            url: ${CONFIG_SCHEMA_REGISTRY_URL:http://localhost:8081}
        auto:
          register:
            schemas: true # Utilizarlo solo en Desarrollo o local
        use:
          latest:
            version: true
