quarkus:
  package:
    jar:
      enabled: true
  http:
    port: 9090
  datasource:
    db-kind: mysql
    username: root
    password: 123456789
    reactive:
      url: vertx-reactive:mysql://localhost:3307/phone_recharge_db
  hibernate-orm:
    database:
      generation: none
      version-check:
        enabled: false
