quarkus:
  package:
    jar:
      enabled: true
  http:
    port: 8084
  datasource:
    db-kind: mysql
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456789}
    reactive:
      url: vertx-reactive:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/phone_recharge_db
  hibernate-orm:
    database:
      generation: none
      version-check:
        enabled: false
